# -*- coding: utf-8 -*-
"""VERSION_FINAL_DETECCION_DE_FRAUDE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RIEMEhZHYQK6ojon7y64vx883KjW5Ce3

### Setup: Drive, librerías y constantes del proyecto
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import gc
import numpy as np
import pandas as pd


CARPETA       = "/content/drive/MyDrive/Archivos_CSV_Deteccion_Fraude"
TAMANO_TRAIN  = 100_000        # filas del train reducido (estratificado)
SPLIT_RATIO   = 0.80           # 80% train / 20% test temporal
RANDOM_STATE  = 42

# --- Verificacion de archivos -----
print("Archivos en la carpeta:")
for f in sorted(os.listdir(CARPETA)):
    ruta = os.path.join(CARPETA, f)
    print(f"  {f:35s}  {os.path.getsize(ruta)/1024**2:8.1f} MB")

"""### Carga y optimización de train_transaction"""

train_transaction = pd.read_csv(
    os.path.join(CARPETA, "train_transaction.csv"),
    low_memory=False
)

# Downcast de tipos para ahorrar memoria
for col in train_transaction.select_dtypes(include=["float64"]).columns:
    train_transaction[col] = train_transaction[col].astype("float32")

for col in train_transaction.select_dtypes(include=["int64"]).columns:
    train_transaction[col] = pd.to_numeric(train_transaction[col], downcast="integer")

for col in train_transaction.select_dtypes(include=["object"]).columns:
    train_transaction[col] = train_transaction[col].astype("category")

# Reporte
print(f"Dimensiones : {train_transaction.shape}")
print(f"Memoria     : {train_transaction.memory_usage(deep=True).sum()/1024**2:.1f} MB")
print(f"\nDistribución isFraud:")
print(train_transaction['isFraud'].value_counts().to_string())
print(f"% fraude    : {train_transaction['isFraud'].mean()*100:.4f}%")

"""### Orden temporal, split principal y submuestreo estratificado del train"""

# Orden cronologico
train_transaction = (
    train_transaction
    .sort_values("TransactionDT")
    .reset_index(drop=True)
)

# Split temporal 80/20
split_idx = int(len(train_transaction) * SPLIT_RATIO)
tx_train  = train_transaction.iloc[:split_idx].copy()
tx_test   = train_transaction.iloc[split_idx:].copy()

print("--- Split temporal ---")
print(f"tx_train : {tx_train.shape}   fraude: {tx_train['isFraud'].mean()*100:.4f}%")
print(f"tx_test  : {tx_test.shape}    fraude: {tx_test['isFraud'].mean()*100:.4f}%")

# Submuestreo estratificado SOLO en train (preservando proporción de fraude)
idx_fr = tx_train[tx_train["isFraud"] == 1].index
idx_nf = tx_train[tx_train["isFraud"] == 0].index

n_fr = int(TAMANO_TRAIN * tx_train["isFraud"].mean())
n_nf = TAMANO_TRAIN - n_fr

rng = np.random.RandomState(RANDOM_STATE)
sel_idx = np.sort(np.concatenate([
    rng.choice(idx_fr, n_fr, replace=False),
    rng.choice(idx_nf, n_nf, replace=False),
]))

tx_train_small = tx_train.iloc[sel_idx].reset_index(drop=True)

print("\n--- Train reducido --")
print(f"tx_train_small : {tx_train_small.shape}")
print(f"fraude         : {tx_train_small['isFraud'].mean()*100:.4f}%")

# Liberar el dataset completo (ya no se necesita)
del train_transaction, tx_train
gc.collect()

"""###  Carga y optimización de train_identity"""

train_identity = pd.read_csv(
    os.path.join(CARPETA, "train_identity.csv"),
    low_memory=False
)

for col in train_identity.select_dtypes(include=["float64"]).columns:
    train_identity[col] = train_identity[col].astype("float32")

for col in train_identity.select_dtypes(include=["int64"]).columns:
    train_identity[col] = pd.to_numeric(train_identity[col], downcast="integer")

for col in train_identity.select_dtypes(include=["object"]).columns:
    train_identity[col] = train_identity[col].astype("category")

print(f"Dimensiones : {train_identity.shape}")
print(f"Memoria     : {train_identity.memory_usage(deep=True).sum()/1024**2:.1f} MB")

"""### Merge final, verificación de cobertura y limpieza"""

# LEFT JOIN identity sobre train reducido y sobre test completo
train_df = tx_train_small.merge(train_identity, on="TransactionID", how="left")
test_df  = tx_test.merge(train_identity,        on="TransactionID", how="left")

# Verificacion de cobertura real de identity (post-merge)
cov_train = train_df['DeviceType'].notna().mean() * 100
cov_test  = test_df['DeviceType'].notna().mean()  * 100

print("--- Dimensiones finales ---")
print(f"train_df : {train_df.shape}")
print(f"test_df  : {test_df.shape}")

print("\n--- Cobertura de identity (post-merge) ---")
print(f"train_df : {train_df['DeviceType'].notna().sum():>6,} / {len(train_df):>6,}  ({cov_train:.2f}%)")
print(f"test_df  : {test_df['DeviceType'].notna().sum():>6,} / {len(test_df):>6,}  ({cov_test:.2f}%)")

print("\n--- Memoria ---")
print(f"train_df : {train_df.memory_usage(deep=True).sum()/1024**2:.1f} MB")
print(f"test_df  : {test_df.memory_usage(deep=True).sum()/1024**2:.1f} MB")

print("\n--- Tasa de fraude final ---")
print(f"train_df : {train_df['isFraud'].mean()*100:.4f}%")
print(f"test_df  : {test_df['isFraud'].mean()*100:.4f}%")

# Eliminar de memoria todo lo intermedio
del train_identity, tx_train_small, tx_test
gc.collect()

# Vista previaa
print("\n--- Primeras filas de train_df ---")
train_df.head()

"""### Separación inicial para modelado"""

# Referencia temporal
train_dt_ref = train_df["TransactionDT"].copy()
test_dt_ref  = test_df["TransactionDT"].copy()

# Variables objetivo
y_train = train_df["isFraud"].copy()
y_test  = test_df["isFraud"].copy()

# Variables predictoras
X_train = train_df.drop(columns=["TransactionID", "TransactionDT", "isFraud"]).copy()
X_test  = test_df.drop(columns=["TransactionID", "TransactionDT", "isFraud"]).copy()

print("--- Dimensiones para modelado ---")
print(f"X_train: {X_train.shape}")
print(f"X_test : {X_test.shape}")
print(f"y_train fraude: {y_train.mean()*100:.4f}%")
print(f"y_test  fraude: {y_test.mean()*100:.4f}%")

"""### Eliminación de columnas con demasiados valores nulos"""

missing_ratio = X_train.isnull().mean().sort_values(ascending=False)
cols_nulos_altos = missing_ratio[missing_ratio > 0.90].index.tolist()

X_train = X_train.drop(columns=cols_nulos_altos)
X_test  = X_test.drop(columns=cols_nulos_altos)

print("--- Eliminacion por cantidad de valores nulos altos ---")
print(f"Columnas eliminadas: {len(cols_nulos_altos)}")
print("Primeras columnas eliminadas:", cols_nulos_altos[:15])
print(f"Nuevo tamaño X_train: {X_train.shape}")
print(f"Nuevo tamaño X_test : {X_test.shape}")

"""### Identificación de tipos y eliminación de columnas altamente correlacionadas"""

num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = X_train.select_dtypes(exclude=[np.number]).columns.tolist()

corr_matrix = X_train[num_cols].corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
cols_correladas = [c for c in upper.columns if (upper[c] > 0.90).any()]

X_train = X_train.drop(columns=cols_correladas)
X_test  = X_test.drop(columns=cols_correladas)

# Actualizar listas de columnas
num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = X_train.select_dtypes(exclude=[np.number]).columns.tolist()

print("--- Tipos de variables ---")
print(f"Numéricas   : {len(num_cols)}")
print(f"Categóricas : {len(cat_cols)}")

print("\n--- Eliminación por correlación alta ---")
print(f"Columnas eliminadas: {len(cols_correladas)}")
print("Primeras columnas eliminadas:", cols_correladas[:15])

print(f"\nTamaño final tras limpieza estructural:")
print(f"X_train: {X_train.shape}")
print(f"X_test : {X_test.shape}")

# Liberar la matriz de correlación (puede pesar bastante)
del corr_matrix, upper
gc.collect()

"""###  Registro de decisiones tomadas"""

registro_preprocesamiento = {
    "columnas_eliminadas_nulos": cols_nulos_altos,
    "columnas_eliminadas_correlacion": cols_correladas,
    "n_columnas_finales_train": X_train.shape[1],
    "n_columnas_finales_test": X_test.shape[1],
    "n_numericas_finales": len(num_cols),
    "n_categoricas_finales": len(cat_cols),
}

print("--- Resumen de decisiones ---")
for k, v in registro_preprocesamiento.items():
    if isinstance(v, list):
        print(f"{k}: {len(v)} elementos")
    else:
        print(f"{k}: {v}")

"""### Imputación y clasificación por cardinalidad

"""

# Imputacion de variiables numéricas con mediana de train
medianas_train = X_train[num_cols].median()
X_train[num_cols] = X_train[num_cols].fillna(medianas_train)
X_test[num_cols]  = X_test[num_cols].fillna(medianas_train)

# Imputacion de variables categoricas con etiqueta Missing
# (convertimos a object para evitar problemas con dtype category)
for col in cat_cols:
    X_train[col] = X_train[col].astype("object").fillna("Missing")
    X_test[col]  = X_test[col].astype("object").fillna("Missing")

# Clasificacion de categooricas por cardinalidad
low_card_cols  = [c for c in cat_cols if X_train[c].nunique() <= 10]
high_card_cols = [c for c in cat_cols if X_train[c].nunique() > 10]

print("--- Imputación completada ---")
print(f"Variables numéricas imputadas   : {len(num_cols)}")
print(f"Variables categóricas imputadas : {len(cat_cols)}")
print("\n--- Clasificación por cardinalidad ---")
print(f"Baja cardinalidad (<=10) : {len(low_card_cols)}")
print(f"Media/alta cardinalidad  : {len(high_card_cols)}")
print("\nPrimeras variables de baja cardinalidad:")
print(low_card_cols[:15])
print("\nPrimeras variables de media/alta cardinalidad:")
print(high_card_cols[:15])

"""### Codificación categórica"""

# One-hot encoding para baja cardinalidad
X_train = pd.get_dummies(X_train, columns=low_card_cols, drop_first=False)
X_test  = pd.get_dummies(X_test,  columns=low_card_cols, drop_first=False)

# Frequency encoding para media/alta cardinalidad
for col in high_card_cols:
    freq_map = X_train[col].value_counts(normalize=True)
    X_train[col] = X_train[col].map(freq_map).astype("float32")
    X_test[col]  = X_test[col].map(freq_map).fillna(0).astype("float32")

# Alinear columnas entre train y test
X_train, X_test = X_train.align(X_test, join="left", axis=1, fill_value=0)

print("--- Codificación completada ---")
print(f"Dimensión final X_train: {X_train.shape}")
print(f"Dimensión final X_test : {X_test.shape}")

"""### Verificación final del preprocesamiento


"""

# Convertir columnas booleanas (generadas por get_dummies) a uint8
bool_cols = X_train.select_dtypes(include=["bool"]).columns.tolist()
if bool_cols:
    X_train[bool_cols] = X_train[bool_cols].astype("uint8")
    X_test[bool_cols]  = X_test[bool_cols].astype("uint8")

# Verificaciones
nulos_train = X_train.isnull().sum().sum()
nulos_test  = X_test.isnull().sum().sum()
inf_train   = np.isinf(X_train.select_dtypes(include=[np.number])).sum().sum()
inf_test    = np.isinf(X_test.select_dtypes(include=[np.number])).sum().sum()

print("--- Verificación final ---")
print(f"Nulos en X_train: {nulos_train}")
print(f"Nulos en X_test : {nulos_test}")
print(f"Infinitos en X_train: {inf_train}")
print(f"Infinitos en X_test : {inf_test}")

print("\nDimensiones listas para modelado:")
print(f"X_train: {X_train.shape}")
print(f"X_test : {X_test.shape}")
print(f"y_train: {y_train.shape}")
print(f"y_test : {y_test.shape}")

"""### Validación temporal interna dentro del train reducido"""

# Validación temporal interna
split_val_idx = int(len(X_train) * 0.85)

X_subtrain = X_train.iloc[:split_val_idx].copy()
X_val      = X_train.iloc[split_val_idx:].copy()
y_subtrain = y_train.iloc[:split_val_idx].copy()
y_val      = y_train.iloc[split_val_idx:].copy()

print("--- Validación temporal interna ---")
print(f"X_subtrain: {X_subtrain.shape}   fraude: {y_subtrain.mean()*100:.4f}%")
print(f"X_val     : {X_val.shape}        fraude: {y_val.mean()*100:.4f}%")

"""###  Construcción de la rama manual y la rama referencial"""

# Rama referencial (sin escalado obligatorio)
X_subtrain_ref = X_subtrain.copy()
X_val_ref      = X_val.copy()
X_test_ref     = X_test.copy()

# Rama manual (se escalara)
X_subtrain_manual = X_subtrain.copy()
X_val_manual      = X_val.copy()
X_test_manual     = X_test.copy()

print("--- Ramas creadas ---")
print(f"Rama manual      - X_subtrain_manual: {X_subtrain_manual.shape}")
print(f"Rama referencial - X_subtrain_ref   : {X_subtrain_ref.shape}")

"""### Escalado para la rama manual"""

# Detectar columnas numeericas en la rama manual
num_cols_manual = X_subtrain_manual.select_dtypes(include=[np.number]).columns.tolist()

# Media y desviacion estndar calculadas solo con subtrain
mean_manual = X_subtrain_manual[num_cols_manual].mean()
std_manual  = X_subtrain_manual[num_cols_manual].std().replace(0, 1)

# Escalado (forzando float32 para evitar duplicar el tamaño en la memoria)
X_subtrain_manual[num_cols_manual] = (
    (X_subtrain_manual[num_cols_manual] - mean_manual) / std_manual
).astype("float32")

X_val_manual[num_cols_manual] = (
    (X_val_manual[num_cols_manual] - mean_manual) / std_manual
).astype("float32")

X_test_manual[num_cols_manual] = (
    (X_test_manual[num_cols_manual] - mean_manual) / std_manual
).astype("float32")

print("--- Rama manual escalada ---")
print(f"X_subtrain_manual: {X_subtrain_manual.shape}")
print(f"X_val_manual     : {X_val_manual.shape}")
print(f"X_test_manual    : {X_test_manual.shape}")

"""### Verificación final de las ramas

"""

print("--- Verificación rama manual ---")
print(f"Nulos X_subtrain_manual: {X_subtrain_manual.isnull().sum().sum()}")
print(f"Nulos X_val_manual     : {X_val_manual.isnull().sum().sum()}")
print(f"Nulos X_test_manual    : {X_test_manual.isnull().sum().sum()}")

print("\n--- Verificación rama referencial ---")
print(f"Nulos X_subtrain_ref: {X_subtrain_ref.isnull().sum().sum()}")
print(f"Nulos X_val_ref     : {X_val_ref.isnull().sum().sum()}")
print(f"Nulos X_test_ref    : {X_test_ref.isnull().sum().sum()}")

print("\n--- Dimensiones finales ---")
print(f"Manual      - subtrain: {X_subtrain_manual.shape}, val: {X_val_manual.shape}, test: {X_test_manual.shape}")
print(f"Referencial - subtrain: {X_subtrain_ref.shape}, val: {X_val_ref.shape}, test: {X_test_ref.shape}")

"""### Funciones auxiliares para la comparación preliminar"""

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

def sigmoid(z):
    z = np.clip(z, -500, 500)
    return 1.0 / (1.0 + np.exp(-z))

def predict_proba_lr(X, w, b):
    return sigmoid(X @ w + b)

def predict_lr(X, w, b, threshold=0.5):
    probs = predict_proba_lr(X, w, b)
    return (probs >= threshold).astype(np.uint8)

def confusion_matrix_binary(y_true, y_pred):
    tp = np.sum((y_true == 1) & (y_pred == 1))
    tn = np.sum((y_true == 0) & (y_pred == 0))
    fp = np.sum((y_true == 0) & (y_pred == 1))
    fn = np.sum((y_true == 1) & (y_pred == 0))
    return tp, tn, fp, fn

def precision_recall_f1_mcc(y_true, y_pred):
    tp, tn, fp, fn = confusion_matrix_binary(y_true, y_pred)

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

    denom = np.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))
    mcc = ((tp * tn) - (fp * fn)) / denom if denom > 0 else 0.0

    return {
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "mcc": mcc,
        "tp": tp,
        "tn": tn,
        "fp": fp,
        "fn": fn
    }

def auc_roc_manual(y_true, y_prob):
    order = np.argsort(-y_prob)
    y_sorted = y_true[order]

    P = np.sum(y_true == 1)
    N = np.sum(y_true == 0)

    if P == 0 or N == 0:
        return 0.0

    tp = 0
    fp = 0
    tpr = [0.0]
    fpr = [0.0]

    for yi in y_sorted:
        if yi == 1:
            tp += 1
        else:
            fp += 1
        tpr.append(tp / P)
        fpr.append(fp / N)

    tpr.append(1.0)
    fpr.append(1.0)

    return np.trapz(tpr, fpr)

def auc_pr_manual(y_true, y_prob):
    order = np.argsort(-y_prob)
    y_sorted = y_true[order]

    P = np.sum(y_true == 1)
    if P == 0:
        return 0.0

    tp = 0
    fp = 0
    recall_vals = [0.0]
    precision_vals = [1.0]

    for yi in y_sorted:
        if yi == 1:
            tp += 1
        else:
            fp += 1

        recall = tp / P
        precision = tp / (tp + fp)

        recall_vals.append(recall)
        precision_vals.append(precision)

    return np.trapz(precision_vals, recall_vals)

"""###  Regresión Logística manual básica"""

def train_logistic_basic(X_train, y_train, alpha=0.01, lambda_reg=0.01, epochs=200):
    X_np = X_train.to_numpy(dtype=np.float32)
    y_np = y_train.to_numpy(dtype=np.float32)
    n_samples, n_features = X_np.shape

    w = np.zeros(n_features, dtype=np.float32)
    b = 0.0

    n1 = np.sum(y_np == 1)
    n0 = np.sum(y_np == 0)
    n  = len(y_np)
    w1 = n / (2 * n1)
    w0 = n / (2 * n0)

    for epoch in range(epochs):
        y_prob = predict_proba_lr(X_np, w, b)
        sample_weights = np.where(y_np == 1, w1, w0).astype(np.float32)
        error = (y_prob - y_np) * sample_weights
        dw = (X_np.T @ error) / n + (lambda_reg / n) * w
        db = np.mean(error)
        w -= alpha * dw
        b -= alpha * db

    return w, b

alpha_lr   = 0.01
lambda_lr  = 0.01
epochs_lr  = 200

w_lr, b_lr = train_logistic_basic(
    X_subtrain_manual, y_subtrain,
    alpha=alpha_lr, lambda_reg=lambda_lr, epochs=epochs_lr
)

lr_probs = predict_proba_lr(X_test_manual.to_numpy(dtype=np.float32), w_lr, b_lr)
lr_pred  = (lr_probs >= 0.5).astype(np.uint8)

y_test_np = y_test.to_numpy()
lr_metrics = precision_recall_f1_mcc(y_test_np, lr_pred)
lr_auc_roc = auc_roc_manual(y_test_np, lr_probs)
lr_auprc   = auc_pr_manual(y_test_np, lr_probs)

print("--- Regresión Logística manual ---")
print(f"Precision: {lr_metrics['precision']:.4f}")
print(f"Recall   : {lr_metrics['recall']:.4f}")
print(f"F1-score : {lr_metrics['f1']:.4f}")
print(f"MCC      : {lr_metrics['mcc']:.4f}")
print(f"AUC-ROC  : {lr_auc_roc:.4f}")
print(f"AUPRC    : {lr_auprc:.4f}")

"""### KNN manual"""

def knn_predict_proba_chunked(X_train, y_train, X_test, k=5, chunk_size=500):
    Xtr = X_train.to_numpy(dtype=np.float32)
    ytr = y_train.to_numpy(dtype=np.uint8)
    Xte = X_test.to_numpy(dtype=np.float32)

    train_norm = np.sum(Xtr ** 2, axis=1)[None, :]
    probs = []

    for start in range(0, len(Xte), chunk_size):
        end = min(start + chunk_size, len(Xte))
        X_chunk = Xte[start:end]

        # ||x - y||^2 = ||x||^2 + ||y||^2 - 2 * x·y
        chunk_norm = np.sum(X_chunk ** 2, axis=1)[:, None]
        cross      = X_chunk @ Xtr.T
        dists_sq   = np.maximum(chunk_norm + train_norm - 2 * cross, 0)

        idx_neighbors  = np.argpartition(dists_sq, kth=k-1, axis=1)[:, :k]
        neighbor_labels = ytr[idx_neighbors]
        chunk_probs    = neighbor_labels.mean(axis=1)
        probs.append(chunk_probs)

    return np.concatenate(probs)

k_knn = 5
knn_probs = knn_predict_proba_chunked(
    X_subtrain_manual, y_subtrain, X_test_manual,
    k=k_knn, chunk_size=500
)
knn_pred = (knn_probs >= 0.5).astype(np.uint8)

knn_metrics = precision_recall_f1_mcc(y_test_np, knn_pred)
knn_auc_roc = auc_roc_manual(y_test_np, knn_probs)
knn_auprc   = auc_pr_manual(y_test_np, knn_probs)

print("--- KNN manual ---")
print(f"Precision: {knn_metrics['precision']:.4f}")
print(f"Recall   : {knn_metrics['recall']:.4f}")
print(f"F1-score : {knn_metrics['f1']:.4f}")
print(f"MCC      : {knn_metrics['mcc']:.4f}")
print(f"AUC-ROC  : {knn_auc_roc:.4f}")
print(f"AUPRC    : {knn_auprc:.4f}")

"""###  Árbol de Decisión y Random Forest referenciales"""

dt_model = DecisionTreeClassifier(
    class_weight="balanced", random_state=42, max_depth=8
)
rf_model = RandomForestClassifier(
    n_estimators=50, max_depth=10, class_weight="balanced",
    random_state=42, n_jobs=-1
)

# Arbol de Decision
dt_model.fit(X_subtrain_ref, y_subtrain)
dt_probs = dt_model.predict_proba(X_test_ref)[:, 1]
dt_pred  = (dt_probs >= 0.5).astype(np.uint8)

dt_metrics = precision_recall_f1_mcc(y_test_np, dt_pred)
dt_auc_roc = auc_roc_manual(y_test_np, dt_probs)
dt_auprc   = auc_pr_manual(y_test_np, dt_probs)

print("--- Árbol de Decisión referencial ---")
print(f"Precision: {dt_metrics['precision']:.4f}")
print(f"Recall   : {dt_metrics['recall']:.4f}")
print(f"F1-score : {dt_metrics['f1']:.4f}")
print(f"MCC      : {dt_metrics['mcc']:.4f}")
print(f"AUC-ROC  : {dt_auc_roc:.4f}")
print(f"AUPRC    : {dt_auprc:.4f}")

# Random Forest
rf_model.fit(X_subtrain_ref, y_subtrain)
rf_probs = rf_model.predict_proba(X_test_ref)[:, 1]
rf_pred  = (rf_probs >= 0.5).astype(np.uint8)

rf_metrics = precision_recall_f1_mcc(y_test_np, rf_pred)
rf_auc_roc = auc_roc_manual(y_test_np, rf_probs)
rf_auprc   = auc_pr_manual(y_test_np, rf_probs)

print("\n--- Random Forest referencial ---")
print(f"Precision: {rf_metrics['precision']:.4f}")
print(f"Recall   : {rf_metrics['recall']:.4f}")
print(f"F1-score : {rf_metrics['f1']:.4f}")
print(f"MCC      : {rf_metrics['mcc']:.4f}")
print(f"AUC-ROC  : {rf_auc_roc:.4f}")
print(f"AUPRC    : {rf_auprc:.4f}")

"""###  Tabla comparativa preliminar

"""

resultados_preliminares = pd.DataFrame([
    {
        "Modelo": "Regresión Logística (manual)",
        "Precision": lr_metrics["precision"],
        "Recall": lr_metrics["recall"],
        "F1": lr_metrics["f1"],
        "MCC": lr_metrics["mcc"],
        "AUC_ROC": lr_auc_roc,
        "AUPRC": lr_auprc
    },
    {
        "Modelo": "KNN (manual)",
        "Precision": knn_metrics["precision"],
        "Recall": knn_metrics["recall"],
        "F1": knn_metrics["f1"],
        "MCC": knn_metrics["mcc"],
        "AUC_ROC": knn_auc_roc,
        "AUPRC": knn_auprc
    },
    {
        "Modelo": "Árbol de Decisión (referencial)",
        "Precision": dt_metrics["precision"],
        "Recall": dt_metrics["recall"],
        "F1": dt_metrics["f1"],
        "MCC": dt_metrics["mcc"],
        "AUC_ROC": dt_auc_roc,
        "AUPRC": dt_auprc
    },
    {
        "Modelo": "Random Forest (referencial)",
        "Precision": rf_metrics["precision"],
        "Recall": rf_metrics["recall"],
        "F1": rf_metrics["f1"],
        "MCC": rf_metrics["mcc"],
        "AUC_ROC": rf_auc_roc,
        "AUPRC": rf_auprc
    }
])

resultados_preliminares = resultados_preliminares.sort_values(
    by="F1",
    ascending=False
).reset_index(drop=True)

resultados_preliminares

"""### Resumen rápido del comportamiento observado

"""

mejor_f1 = resultados_preliminares.iloc[0]
mejor_recall = resultados_preliminares.sort_values(by="Recall", ascending=False).iloc[0]
mejor_precision = resultados_preliminares.sort_values(by="Precision", ascending=False).iloc[0]

print("--- Resumen preliminar ---")
print(f"Mejor F1-score : {mejor_f1['Modelo']} ({mejor_f1['F1']:.4f})")
print(f"Mejor Recall   : {mejor_recall['Modelo']} ({mejor_recall['Recall']:.4f})")
print(f"Mejor Precision: {mejor_precision['Modelo']} ({mejor_precision['Precision']:.4f})")